# Generated by Django 4.2.5 on 2023-09-29 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_item_list_delete_choice_delete_question_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
